name: ExtraDatabasesH2
version: '10.0.0'
main: com.github.hoshikurama.extradatabases.h2.BukkitPlugin
api-version: '1.19'
authors: [HoshiKurama]
folia-supported: true
dependencies:
    server:
      TicketManager:
        load: AFTER
        required: false
        join-classpath: true