name: ExtraDatabasesH2
version: '10.0.1'
main: com.github.hoshikurama.extradatabases.h2.BukkitPlugin
api-version: '1.19'
authors: [HoshiKurama]
folia-supported: true
dependencies:
  server:
    TicketManager:
      required: true
      load: BEFORE
      join-classpath: true