name: ExtraDatabasesH2
version: '11.1.0'
main: com.github.hoshikurama.extradatabases.h2.BukkitPlugin
api-version: '1.21'
authors: [HoshiKurama]
folia-supported: true
dependencies:
  server:
    TicketManager:
      required: true
      load: AFTER
      join-classpath: false
    TicketManagerCore:
      required: true
      load: BEFORE
      join-classpath: true