name: ExtraDatabasesMySQL
version: '10.0.3'
main: com.github.hoshikurama.extradatabases.mysql.BukkitPlugin
api-version: '1.19'
authors: [HoshiKurama]
folia-supported: true
dependencies:
  server:
    TicketManager:
      required: true
      load: BEFORE
      join-classpath: true