name: ExtraDatabasesMySQL
version: '11.0.0'
main: com.github.hoshikurama.extradatabases.mysql.BukkitPlugin
api-version: '1.19'
authors: [HoshiKurama]
folia-supported: true
dependencies:
  server:
    TicketManager:
      required: true
      load: AFTER
      join-classpath: false
    TicketManagerCore:
      required: true
      load: BEFORE
      join-classpath: true