name: ExtraDatabasesMySQL
version: 11.1.0
main: com.github.hoshikurama.extradatabases.mysql.BukkitPlugin
api-version: 1.21
authors: [HoshiKurama]
depend: [TicketManagerCore]
loadbefore: [TicketManager]