name: ExtraDatabasesMySQL
version: 11.0.1
main: com.github.hoshikurama.extradatabases.mysql.BukkitPlugin
api-version: 1.18
authors: [HoshiKurama]
depend: [TicketManagerCore]
loadbefore: [TicketManager]